# Generated by Django 4.2 on 2023-05-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='user/')),
            ],
            options={
                'db_table': 'user_tb',
            },
        ),
    ]
