# Generated by Django 4.2 on 2023-05-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/user/default_user.png', null=True, upload_to='user/'),
        ),
    ]
